# Generated by Django 4.2.13 on 2024-05-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_client_certificate_of_incorporation_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='licenses',
            field=models.IntegerField(default=0),
        ),
    ]
