# Generated by Django 4.2.13 on 2024-06-19 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_clicked_notification_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp', 'read']},
        ),
    ]
